/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.server.locksettings;

import static com.google.common.truth.Truth.assertThat;

import android.platform.test.annotations.Presubmit;

import androidx.test.filters.SmallTest;
import androidx.test.runner.AndroidJUnit4;

import libcore.util.HexEncoding;

import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.Arrays;

@SmallTest
@Presubmit
@RunWith(AndroidJUnit4.class)
public class SyntheticPasswordCryptoTest {

    private static final byte[] PERSONALIZATION = "personalization".getBytes();
    private static final byte[] KEY = "key".getBytes();
    private static final byte[] MESSAGE = "message".getBytes();

    @Test
    public void testPersonalizedHash() {
        byte[] actualHash = SyntheticPasswordCrypto.personalizedHash(PERSONALIZATION, MESSAGE);
        // This expected hash was computed using:
        //     sha512sum <(echo -n "personalization"; head -c 113 /dev/zero; echo -n "message")
        byte[] expectedHash =
                HexEncoding.decode(
                        "8d72efd6c91451175bda82675e2c05f6f7b3eb61d5e3101a692a5c229e56f65a457d000a"
                                + "7da677716866a2bfe3e503721a1a1fcc20f108677beed8ff458425fc");
        assertThat(actualHash).isEqualTo(expectedHash);
    }

    @Test
    public void testEncryptAndDecryptRoundTrip() {
        byte[] ciphertext = SyntheticPasswordCrypto.encrypt(KEY, PERSONALIZATION, MESSAGE);

        byte[] decryptedMessage = SyntheticPasswordCrypto.decrypt(KEY, PERSONALIZATION, ciphertext);

        assertThat(decryptedMessage).isEqualTo(MESSAGE);
    }

    // This tests that encrypt() expands the message by the amount expected for AES-GCM and doesn't
    // leave a copy of the plaintext in the message. Since the encryption is non-deterministic, this
    // cannot be be an exact test for the output.
    @Test
    public void testEncrypt() {
        final int ivSize = 12;
        final int authTagSize = 16;
        final int expectedOverhead = ivSize + authTagSize;

        byte[] ciphertext = SyntheticPasswordCrypto.encrypt(KEY, PERSONALIZATION, MESSAGE);
        assertThat(ciphertext.length).isEqualTo(MESSAGE.length + expectedOverhead);

        // Note: the false positive rate for this part is expectedOverhead*(1/256)**MESSAGE.length =
        // 3.9e-16, which is low enough to be acceptable.
        for (int i = 0; i < ciphertext.length - MESSAGE.length; i++) {
            byte[] slice = Arrays.copyOfRange(ciphertext, i, i + MESSAGE.length);
            assertThat(slice).isNotEqualTo(MESSAGE);
        }
    }

    // This tests for non-backwards-compatible changes to decrypt(). To do this, it decrypts a
    // ciphertext that was originally generated by encrypt() but has been hardcoded into the test.
    @Test
    public void testDecrypt() {
        byte[] ciphertext =
                HexEncoding.decode(
                        "2ab721b94642a5646195c79361b5a090badfbb51dc4959097400b516c7f99fa664b4f6");

        byte[] decryptedMessage = SyntheticPasswordCrypto.decrypt(KEY, PERSONALIZATION, ciphertext);
        assertThat(decryptedMessage).isEqualTo(MESSAGE);
    }
}
