# Copyright (C) 2025 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http:www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

metric_spec: {
  id: "avg_runtime_per_uitracing_slice"
  dimensions: "slice_name"
  value: "avg_runtime"
  query: {
    id: "duration_per_process"
    inner_query: {
      simple_slices: {
         slice_name_glob: "UiTracing::*"
      }
      select_columns: { column_name: "dur" }
      select_columns: { column_name: "slice_name" }
    }
    group_by: {
      column_names: "slice_name"
      aggregates: {
        column_name: "dur"
        # TODO (b/416488773): Change this to MEDIAN to be more robust against outliers
        op: MEAN
        result_column_name: "avg_runtime"
      }
    }
    select_columns: { column_name: "slice_name" }
    select_columns: { column_name: "avg_runtime" }
  }
}
