/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.server.locksettings.recoverablekeystore.certificate;

import android.content.Context;

import androidx.test.InstrumentationRegistry;

import com.google.common.io.ByteStreams;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.util.Base64;
import java.util.Date;

/** Constants used by the tests in the folder. */
public final class TestData {

    private static final String TEST_FILE_FOLDER_NAME = "KeyStoreRecoveryControllerTest";

    private TestData() {}

    // Some test data that is generated by using OpenSSL command line tools.
    private static final String ROOT_CA_TRUSTED_BASE64 = ""
            + "MIIJbzCCBVegAwIBAgIUa9Srsckglxg6KqAVtN+GuM5y3eQwDQYJKoZIhvcNAQEN"
            + "BQAwIDEeMBwGA1UEAwwVR29vZ2xlIENyeXB0QXV0aFZhdWx0MB4XDTI1MDczMDIz"
            + "NTk0OFoXDTQ1MDcyNTIzNTk0OFowIDEeMBwGA1UEAwwVR29vZ2xlIENyeXB0QXV0"
            + "aFZhdWx0MIIEIjANBgkqhkiG9w0BAQEFAAOCBA8AMIIECgKCBAEA4CMC/m9HXfKL"
            + "IoyAahVfZyPXvAs6dwrzSJalhM+5efLiQ1bOQLeJ5VYPmA1p8CjVnp2AqVsQ4x1e"
            + "w6lNVZdys66nzlyOKURjCyL3SGM/RdsiWXbfOcTVX8iXl7Lj1wqJSs5zzMFFfWpD"
            + "c5auH8vGZz4Gq+bWh2hFXmOc82Yaq+0hOro9mD2WaEiZvZw/dQahFvtcpCfzJvYr"
            + "5hporHbuPgnKK4XYNo0b+8JonhhAkDt4spGAjJeFRGvgXT+KK70hKgIWO2wEujuw"
            + "a3uQWA3jXCIy2yyy4Zlm1nqxFQibK8is2Fv/v0qlS7gL3X6YhrZAtD6R7YKJcpqG"
            + "7M3FGNve5R4egHfeCoZ8JdchXOALhX17IX8QKlJUTCObdz3nljC6FlEUhA2eYn+p"
            + "3TauD4evKxEugihvS6yTFaCKm3APWFJo5OxwDYl1/xaYiWwkHd/aNqeXAFUqmnxF"
            + "dnNPOVt3TApsepW+c9PKVkdICVtiKfzGVz2Q1e7fv4UoVvvKrU2eIrtQ0zZX4ZV8"
            + "WZ3zKVH78sCTxJlGyaInW4xm9iY98CRRj3Cgf9P1JgkRo4SHTTnGw1E4Hv1pdK4J"
            + "d0x44Cd9uiWZQrx50z2JWUlFdRQBXUIiWhCCYDDne7m+ln3EIdZosRUVbHGVgpce"
            + "6Seb3LF81Gd7G8H5bj9s8rMq7aLG3UYxJXyJma7hic1FPZb7QZxctMr78EeDTpzM"
            + "l7JTx73+1aVhUJBC33o2ggKAkBXq/bfvqhOIIiOOePZKQL278CfkwvP68My+dVP7"
            + "mxItOniVQ3lzYhBr3ZJQnE3p4OM4NhGfG/BIgGxnLthYDDZR8UG+LnOd/Ile2v5E"
            + "ran4e8w/ZSaHMeNFtJBkYZgTCJt+MUXGnYIxL/SGyD2LQ0Bkg5RyiXR1A201Qvud"
            + "XaAtLUKuOAs97s1AI8ShiBXGCWJrcT193AK6zb7waxOlBvSOl/wNd+2EnPiTTWfo"
            + "MiVyY8BRASC5HyqdHpkJ5+2O+PoaaWUXJRKUktDRZUdFtrMqwkF2+rPNqkZyKySt"
            + "zOooWx6hziWsuona6uLOxXg4TmFVJap++/dJRYduJWAEaDqx8gEz7EimaQd/FUHg"
            + "M0f34j2cq/nnK/+U5KSv065fO590+B8u3yAoEAz7bgyRpm1L696fL0o0KLQrfudp"
            + "1FDMf9FuWjg9GyOnIi+SQ35ap6UMw3PTjBnj+2pzByrSWe4YiCHTDBXupjuBi7id"
            + "yuLoITbUhdjK17NsS3O5hAUII3PFFXURxjro4RrbGxUEshlCxcF7drfICFZOkpli"
            + "xAVo2QzzkAke8IO1CqxnFJL6g9DrDhOUHhgqnn0tEWfm5fbGiM9O5n3XUVtxy66j"
            + "+SHt2BvhOQIDAQABo4GgMIGdMB0GA1UdDgQWBBTtadKX+TDsvq7HRpyrS+6SC6or"
            + "ojBbBgNVHSMEVDBSgBTtadKX+TDsvq7HRpyrS+6SC6oroqEkpCIwIDEeMBwGA1UE"
            + "AwwVR29vZ2xlIENyeXB0QXV0aFZhdWx0ghRr1KuxySCXGDoqoBW034a4znLd5DAP"
            + "BgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBhjANBgkqhkiG9w0BAQ0FAAOC"
            + "BAEABrbaDgMILsPMmEh0oXpL1jFoIFvyAs7pP5IFzla1bVLcO1+NehrLWbVncbH7"
            + "MrbH8oqZaek/PH2qkIw2EGnX03O6wyM9nPBEs9Pj/jVQ13TnklqKDrdKhmlm+L1w"
            + "MUGP5J4DOSgrDfs4T0v5Lb/0FVeNh/5fbIoYNVz6VjVqdORwAj93R9IEy49bXVrV"
            + "wxMtSmpMogujpn2RVTjiM3VfMWGTzBnsUQaYEFM6bxJkP+FwFSP23JiEgyiBBco8"
            + "GpGBgr/r6qDkIhhW/znVrD4t3hyC5ENmzgrOWEzf9d4SagNAwSHe4VT8aj8UKZEq"
            + "G8HyqPY2b1/O3MAXZcCLPfVSuufdgswoHbnxIBqiZma+JacExOhBV5XrWd/lYRr2"
            + "2hWtZ67Ag5c5uwlCRHB5z8d2SRwQUkL4cEJ7vTjJOpQ1yH+olCmRV4JXCmkIIocy"
            + "LmwYka3raqMlggSbpZ5fB3SkvyUUR0Wq8PCkNZOinitfbcmz0i2Kub6cVBUHM7cn"
            + "XzqnGlNq4ZvMNinCjtzKNMH2fCXPlOWrYZdJnXhFP7uMklCeM0t1/gRS8WR/ybwM"
            + "hm4ZrTV3XdrzYMYUMbcEKT889knoS3niBrw4TJDreRnCoUUkVvkm2xDK3VJu9uhA"
            + "j/Xt2UNg53l3h7WzazNtX8W1BjriVrezbLXH8HiLuLCKTqAqp9i5s1+ni2DoAYto"
            + "zcWmNsHJJArES3+SbjR3l1hhSk/dfelZMecGhloG+NpsVHxye68Q7r6ZW2QV6nLB"
            + "WhIdq0M4IFhvq553uCfxd6X1y2u6pHLVV9eXOpT0iHOp9wNKtOlL934AyE45lJ/o"
            + "kefpaufeFPgzWn87xOHltMkbMuHmhBWC9ec+fdF4ia54pRbQo8Z32FuUqzz2QB7r"
            + "0HNqscli+xZK+FmGvfAywW/QTKUExf3vCBLpxqAsuxVfUiiRVXZva/1YvKhOAFBy"
            + "BRMc1l/Wl8fAPdqR/QiKA0cG9BXdfK0e1wTh7QP3vXEpu9/R5hIbDzVuntA3UYQO"
            + "XeNYf8md+UqDUDCqbOFHIfr2QvaDao0cpDpcKaXGP1eN/6OQwdm4AKzHIERc071i"
            + "R7I1vhrehayMgEo8q1NTDg8AapSbNHpq6Ju+ZKG2f7iSQTdVmMUX1F6QDsMx6EiC"
            + "nM8+W41fX66HXTGfIauVvpxBDHIOKfEKYSUKoPMO7o3cEn4tYsqKdWw5eYPB2AIH"
            + "YKYQMXKbJWQfTC55AF88MFS1qbreWirNlcQfr1ecqVBfylNfKtIvbUzKvVDQ423+"
            + "OL1ercSxIC3pkyYfYdGWJtiiFpwwHqOyxHeuzj9eyUEVz/yWI8/pzv7FP3Bce6um"
            + "tiKOC7IM5++nlEAqPcanSj+Yqg==";
    private static final String ROOT_CA_DIFFERENT_KEY_BASE64 = ""
            + "MIIFJjCCAw6gAwIBAgIJANpazyIWdcb/MA0GCSqGSIb3DQEBCwUAMCAxHjAcBgNV"
            + "BAMMFUdvb2dsZSBDcnlwdEF1dGhWYXVsdDAeFw0xODAxMjEwMzI0MjVaFw0zODAx"
            + "MTYwMzI0MjVaMCAxHjAcBgNVBAMMFUdvb2dsZSBDcnlwdEF1dGhWYXVsdDCCAiIw"
            + "DQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKkAUqkRxdVy9UpI9BjQnylGVPRW"
            + "aQsCwT2iWJ7fuCnQQon1U9nOyw2R5GYKcA8Zy+4Co++6nzRblYYXJG3Fzsj+kxei"
            + "pZGmU11djRJDOhHPPe5jSW37Y0czWaj8jx4xvMim18dGYR7fg6SsOOYXA2y5tlvZ"
            + "xLjvw5qpL62J5bVoAAxjng/Oc2Osu+vpv6M50pUZr0OEiFi59WlwrCCZpf1/80bT"
            + "j2ebCKKAtTYa6+Q+oMGGxb3imSRpmQPtFcvhUPmAaocUjYM/FeIGNRv14oED/aXz"
            + "khuPb+QNkXgk9yiokE10IeAk6oNUNDyuiMNIFy67lUrwc45lv9y0s/8fHj9pvKse"
            + "n3+UOKAuV9atUXLdFKQwnQPt4SOmHPkXoj+5tv32RSvVeYhb0ZOpQPkRhxv4wgs7"
            + "NldNbKhzVDM9K4M5Q2TrPK1yJKrc5/z0bDzmPOcH4AAXPvSt5PZOs0NlXUJ99BcA"
            + "KE1sWArUhipz5mx0hxPTNEM9/8bMb//HkbZtx2log1/fc207W/AFd2FICOpRY+Sb"
            + "CJs9WjstpisppotONvgXxZbZiypGKxpeZOb4s6y3iXtZ0FWXUZrc65b8S06fDVCa"
            + "ZomNFDWhspHFKyueBgU6cR9K97cDo85Juy6RhnouXxi+XpXPdGFwPqVm1glFYos8"
            + "5+Scbwwx69RihN1nAgMBAAGjYzBhMB0GA1UdDgQWBBRoosUAVtfHHeMl8/5x1m2m"
            + "arEOoTAfBgNVHSMEGDAWgBRoosUAVtfHHeMl8/5x1m2marEOoTAPBgNVHRMBAf8E"
            + "BTADAQH/MA4GA1UdDwEB/wQEAwIBhjANBgkqhkiG9w0BAQsFAAOCAgEAYbLVQlsi"
            + "KdzCPsaybSrUtMrmkad8Gy+/QR3J16adxy/2WpxsZ1Su0YA4tFzOSWqt74C0mnUi"
            + "i+3prW7nyEOwezs+NH0SreF4B7tO1FSj157LoHxR2WmCCwul8FfsMi0x6MvEf40v"
            + "bMeLrRAA4ysRITua1INb05fzJpczoaW/Q1lBPXConvolnIMvYsLbCZX4/OhQQCLa"
            + "mJx8mGrt1wcNp7Kvh+3JfuOXw+WGeCuB5sSWBsOUvhfN+8sgyk1Dtq5c7rVKKtqz"
            + "gqHfCNZ+lYa6Vkii7plIcWYJXXa7DMmozX07mrDqdJZEocv6XCoZAKDlJorB8pQT"
            + "im47RF60X/FCHSCK2cHbG5M+kF84xwj5fTLztLM1+RlJSJiGk6jhxJRQ+hl0Vkhp"
            + "+u7UbUDwkUF/CJB3d1Gtfm+QtzFVKe27ClU5YFSKCXRV/K4KnkZqpyG8Py+PUtUf"
            + "WRahp4hkWFkIoLeTnJwgAFRvp/KCtSW0/trI/vfInzqBk/qWIVhxYB8Qv9DXtKBX"
            + "3AZ36HM2dxmjef/rpYRphuEN0ZwYdynsGy9dF0SihbR8curSg67sbtYfyw0xURhU"
            + "Nk99YMy7T0EUYnaki/PIPK/gnJjZTX1FLCyHUR38fDJIWkGB4xr8pSrwmRoPSvNF"
            + "dFr3YlFWwHWd1gXlwJtzeMSuVgoKVtZGmmk=";
    private static final String ROOT_CA_DIFFERENT_COMMON_NAME_BASE64 = ""
            + "MIIJVzCCBT+gAwIBAgIUY+DPOU/KBPgBFbVb06XYE/enI6cwDQYJKoZIhvcNAQEL"
            + "BQAwGDEWMBQGA1UEAwwNV3JvbmcgUm9vdCBDQTAeFw0yNTA3MzEyMjM5MzZaFw00"
            + "NTA3MjYyMjM5MzZaMBgxFjAUBgNVBAMMDVdyb25nIFJvb3QgQ0EwggQiMA0GCSqG"
            + "SIb3DQEBAQUAA4IEDwAwggQKAoIEAQDgIwL+b0dd8osijIBqFV9nI9e8Czp3CvNI"
            + "lqWEz7l58uJDVs5At4nlVg+YDWnwKNWenYCpWxDjHV7DqU1Vl3KzrqfOXI4pRGML"
            + "IvdIYz9F2yJZdt85xNVfyJeXsuPXColKznPMwUV9akNzlq4fy8ZnPgar5taHaEVe"
            + "Y5zzZhqr7SE6uj2YPZZoSJm9nD91BqEW+1ykJ/Mm9ivmGmisdu4+Ccorhdg2jRv7"
            + "wmieGECQO3iykYCMl4VEa+BdP4orvSEqAhY7bAS6O7Bre5BYDeNcIjLbLLLhmWbW"
            + "erEVCJsryKzYW/+/SqVLuAvdfpiGtkC0PpHtgolymobszcUY297lHh6Ad94Khnwl"
            + "1yFc4AuFfXshfxAqUlRMI5t3PeeWMLoWURSEDZ5if6ndNq4Ph68rES6CKG9LrJMV"
            + "oIqbcA9YUmjk7HANiXX/FpiJbCQd39o2p5cAVSqafEV2c085W3dMCmx6lb5z08pW"
            + "R0gJW2Ip/MZXPZDV7t+/hShW+8qtTZ4iu1DTNlfhlXxZnfMpUfvywJPEmUbJoidb"
            + "jGb2Jj3wJFGPcKB/0/UmCRGjhIdNOcbDUTge/Wl0rgl3THjgJ326JZlCvHnTPYlZ"
            + "SUV1FAFdQiJaEIJgMOd7ub6WfcQh1mixFRVscZWClx7pJ5vcsXzUZ3sbwfluP2zy"
            + "syrtosbdRjElfImZruGJzUU9lvtBnFy0yvvwR4NOnMyXslPHvf7VpWFQkELfejaC"
            + "AoCQFer9t++qE4giI4549kpAvbvwJ+TC8/rwzL51U/ubEi06eJVDeXNiEGvdklCc"
            + "Teng4zg2EZ8b8EiAbGcu2FgMNlHxQb4uc538iV7a/kStqfh7zD9lJocx40W0kGRh"
            + "mBMIm34xRcadgjEv9IbIPYtDQGSDlHKJdHUDbTVC+51doC0tQq44Cz3uzUAjxKGI"
            + "FcYJYmtxPX3cArrNvvBrE6UG9I6X/A137YSc+JNNZ+gyJXJjwFEBILkfKp0emQnn"
            + "7Y74+hppZRclEpSS0NFlR0W2syrCQXb6s82qRnIrJK3M6ihbHqHOJay6idrq4s7F"
            + "eDhOYVUlqn7790lFh24lYARoOrHyATPsSKZpB38VQeAzR/fiPZyr+ecr/5TkpK/T"
            + "rl87n3T4Hy7fICgQDPtuDJGmbUvr3p8vSjQotCt+52nUUMx/0W5aOD0bI6ciL5JD"
            + "flqnpQzDc9OMGeP7anMHKtJZ7hiIIdMMFe6mO4GLuJ3K4ughNtSF2MrXs2xLc7mE"
            + "BQgjc8UVdRHGOujhGtsbFQSyGULFwXt2t8gIVk6SmWLEBWjZDPOQCR7wg7UKrGcU"
            + "kvqD0OsOE5QeGCqefS0RZ+bl9saIz07mfddRW3HLrqP5Ie3YG+E5AgMBAAGjgZgw"
            + "gZUwHQYDVR0OBBYEFO1p0pf5MOy+rsdGnKtL7pILqiuiMFMGA1UdIwRMMEqAFO1p"
            + "0pf5MOy+rsdGnKtL7pILqiuioRykGjAYMRYwFAYDVQQDDA1Xcm9uZyBSb290IENB"
            + "ghRj4M85T8oE+AEVtVvTpdgT96cjpzAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB"
            + "/wQEAwIBhjANBgkqhkiG9w0BAQsFAAOCBAEAeCna5iEbIS6o18pu4eeOl8K9BDmI"
            + "eKlCZeOzgLgCANPy3x2G4mT4n6gjcoIyXwpEpLLrf04Pz/x/T0J02REtHKUrQCZU"
            + "2CQYhM2SUiHs6oNmoQZamCOF2whRpk9Bo+AUoIzR3TwNOmAdi7q5EGk9yNhgHcN8"
            + "CUhP+38+Xo4Sb9D34mdEKQdQgMvsxOodePw3Mwh2oBE3KTy5pNqweVMUt5TlXyNO"
            + "Mj4pNJnZ5xN3ucfLUXIIlAaDexS5rX2+Fw9SD7LobMj+dx5w1/xuLIYIaqd/mwBD"
            + "8Ut3rcwIOVtaT4jQck1GAcSOb+j60U4QiHvEiLhMpB1WMNEOOeFWD4q3ySpo5bO6"
            + "Q0l8g0vMLF3qfc7tL5vbU8ipRUebzn9hVF3XSaggtYf4Dni5pVQZeFdc2p4+/fnI"
            + "npDeKDzKYC5GQ7Gty1CTShJk9+cSyKFu9k89bl1IFX5j4xnURIjXbffV5Q3EzF7a"
            + "ivJnFBa9ubpOiOU7luHU+4HHzFQJY7XVMRlTFjTfM01C8T2WnkllbxvxEIxsAisv"
            + "2SfLU8Tsbcry/Fp8/C4ZSjw4rac8ee7b+kSbDxUUlbZOQ+HTVAiaL8whI8bwDEV7"
            + "Kmrr18+YT/vn/1wt2SJ5ZAY3RW4FToT2QjyVx+tIwjhqQKv/NSMrjFK2flKT8l13"
            + "XdQ8vf8Z5B4c0C1NPFc4q6QguJXDIxO7ukALCFFIJ/pZxVi5ecbDy4RD4lnLmaOB"
            + "P8mmTokjzCi97rMh0rUn183o6wCByCdnE2FdzsXkSGf+39vb1w/yLeoTjQKRKuHS"
            + "sQyWoQulcpZkTPTnTo5D8xYs/Bp/hkgLkVRLWQWgfUWxjxcJl+WZyRXNciAliv6c"
            + "2ASN53ZO2rGL4/fAtfZszClLowk6tFU40bLb5GlOPWtyTsWIt0uoMWuGYa24St0T"
            + "9vCRjYYdKlz2gq/8eJP9teVjNzagIw+UCGPZrQtkXlIEh2vc8mbnfyEVv3uNBUUo"
            + "gjNFhkwQgs/+j/+XAICtnI2us1dJYkVTPuIwaMMYS3Cp+cnju1McfmgCb9tXMBKh"
            + "ts5OQBfHUfYm/9JbkO6Tr0hfwaR8yY02h6Eu7+NZdg3OnyUp7haCmM1+ECEnvOCS"
            + "szLWvotxcXTVDUuSQN+0refj44Wwn+acQxHQLRzFQtQp+iQ80HKz/zxtPSvpsD/t"
            + "7CzcWXwz8ehtLtDRGimpavH5DR3JWCOHCj97O/5vQxcKY3xiLH5e5x5rIBKu1VR/"
            + "c5y1FgQvIDlZiy2EIU6mzXu/Yjas88Yg7Sn+4rR+4fURoNRJQ5SX1/sx3TU82KAH"
            + "+YKZmr0Dcixhho0i/jqWjm+QC/jkyvNAo8UTDNxdCMMOLSTKUhXKSuDf2w==";
    private static final String INTERMEDIATE_CA_1_BASE64 = ""
            + "MIIHbTCCA1WgAwIBAgICEAEwDQYJKoZIhvcNAQELBQAwIDEeMBwGA1UEAwwVR29v"
            + "Z2xlIENyeXB0QXV0aFZhdWx0MB4XDTI1MDgwMTAyMjU0N1oXDTM1MDczMDAyMjU0"
            + "N1owLTErMCkGA1UEAwwiR29vZ2xlIENyeXB0QXV0aFZhdWx0IEludGVybWVkaWF0"
            + "ZTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKNPXgjNp2xWRBJxZbXM"
            + "ZqH3bzCuMFggpM1XJ+935hFwjFRrDC47aSujK6M/yeEge9ni0cINOlupC9m1UqoD"
            + "lK4uQmpom9iBlamr7+PDW6yoVI6mk/vf3p62B0wC4aR1019XlGRXp3ctCE8+dpsD"
            + "V0vAWxbEEU8jTSm6DzJdvrO6dNJF9Fn/4tt4QS4Eew37psyWyC+Jm+ELBUhVUrML"
            + "nr8rhMDGrWdjpLql3+92pKBwy+NrXF4SbXpc/dohJ52ER6LLswsE/aSuwHvCH7jR"
            + "Zmyxt5z7hX1in35ngG1OPTRs65UkGDwU8MBjH/58LVjBNqQKeADEHoKHpQdjUiXQ"
            + "mPFmhNR7EdDAHI+/04Z54IIWaUlEW5vOb76zlZhZW22JpldzydvRUyY3VLVN/uj2"
            + "vXqE0rmI/8xhwr3k4uxzw6dfXB9ptfvFCXlhzBSnPBRIot6r93ouPWiu/TknC+Ff"
            + "NDe+0ncekLDcljI5G0k1a7IOqKUYfu1JreO0YWDnhOHZlN+5QLYLWmK18j5zEIvz"
            + "Tej6AnI0x1NHVL/xydlXFGgJ02h2DcE1//IItvfpqWTAlmrp7ilSkWvUYwEh522/"
            + "6b2x7UXTqgaFDa8/VhILP8z2Cd9HRfvbJzWY7PVoHSfsa3+1SAGuUoPGvYdD3pKv"
            + "2UHDi7uwfZ5FKgxAiKg2Rj/pAgMBAAGjgaMwgaAwHQYDVR0OBBYEFN78dd1kcVip"
            + "An4J51ZCt1pJIgDPMFsGA1UdIwRUMFKAFO1p0pf5MOy+rsdGnKtL7pILqiuioSSk"
            + "IjAgMR4wHAYDVQQDDBVHb29nbGUgQ3J5cHRBdXRoVmF1bHSCFGvUq7HJIJcYOiqg"
            + "FbTfhrjOct3kMBIGA1UdEwEB/wQIMAYBAf8CAQEwDgYDVR0PAQH/BAQDAgGGMA0G"
            + "CSqGSIb3DQEBCwUAA4IEAQDUlIrt/eBt4HWGPLMzVBMWNGrMblc+Y209ZmrqAFHo"
            + "WdmBq3pWJ0hUnIyv1Qi273AS7fqwjo/C56uqYF/dBfcija3ShQ5qaqMTmHUxQ+KZ"
            + "MGZRVUV4VAQPoA0N9cFXm3Rq39adCbl3Pz1I3A+bk8w+QC0894w5fioXHxYrthLg"
            + "lA5jNvOlcIG+aWA8cXPGZQork1y2+Xayfixj8lQcmBnKGMgB+kE8fLyNr7c4Ohfh"
            + "tN9u8yrdvaBDL6zat440I2AU199ZiVToVLNTKITrzwIZz1o4PIQa/hZe2C1S3NyG"
            + "feu6QZy6z7seo31at3iLUalGCa2WaLVx3RxpizS/eCsn50AZqg0+otyv221ag8Y0"
            + "h7uNorSqGUpyHHKA4uxWUnfVpBb5qIzAxkT3Gp3D43bsG19J4PAJBKh263Q//zDb"
            + "xCtb7MdiFpnMlkbfdJu1ZsBH9R/MRmRxC5YcsZA341fpwQlRr1RVGtFh9+pf5/ON"
            + "0lNGk1pWdat/+099t33hwkX00uLO9vbNFezwfzUODhhE45mHJrKyhyTYpWB0St6S"
            + "rc2mMislE46xNSPHYMpqz3qog+pRVh4V112gp+v9zx7mcCOUFVAPaZI4r67Hu1Oc"
            + "J/zwZvQbLj+yzunl5rHGRcj1kfedPAQ23j+pQwIYvHnerEhx8eJnWDhW8Z0VrMOD"
            + "ljtOfhaOtDG3Ec+hAjiceZjUXkVKA83ENjZRsqv7pjlZ3jEy0a8V0/rOBBem6FEb"
            + "ORW8mSt3BNPtggY57Pl0hQOrE5rb/4ubBqc58SxiI6XIRp2Dh+PTxaVcXBrvyWM9"
            + "KUNTtyUVrhztteyVd9mwA4UwRyyN4BZq1Sbot32dOhV7ogFpVeYqfFVhOBJZpP8R"
            + "lXI4zn4JHJQMySTZvg7/F5HS+0JuQqpucF0zj3fuY3WlkyrMJ6WsyHwdMCQ/QTPa"
            + "W+/ZdvioytOg+Ue65QhPpX8PvwAHBLiXNotNnyvkl8IQLpkHa+DieDBvX/1bcKSE"
            + "fBin5I0R+mpWKQ+JgSnmLnTrV0ag7g8pFQ6lPbmKCvOGMrs8lYliGV3kDe29/YDB"
            + "TbP0iudIFt3dtmsw1BUzHMj8RXB1tJdmtcljmB3/lnFsyKGSjAYcYFQ34U79psr3"
            + "fh0A6kWhlFeeb9fqaA9ysoOaqrgjrexWCFM9YhU+11C3rPCYmo6ftppA4+X2dZd5"
            + "HZjhlqPHZ4pygl6nx9OR/AoD8/58TYL5n+EbeSQzcptPhE8v5OXHu+zTt1mmncNx"
            + "NPzoZdlDkBMgUaTSRfMEORzaImFhVEhcwBoEVuFjPB432hOW7tE1n+Q1YTV9Yz5G"
            + "yeSfO/R3i0uGcz8lS8q60tVlI0LAH7BtssAFOle25UKD";
    private static final String INTERMEDIATE_CA_2_BASE64 = ""
            + "MIIEdTCCAl2gAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwLTErMCkGA1UEAwwiR29v"
            + "Z2xlIENyeXB0QXV0aFZhdWx0IEludGVybWVkaWF0ZTAeFw0yNTA4MDEwMjM3NTRa"
            + "Fw0zMDA3MzEwMjM3NTRaMDoxODA2BgNVBAMML0dvb2dsZSBDcnlwdEF1dGhWYXVs"
            + "dCBJbnRlcm1lZGlhdGUgSW50ZXJtZWRpYXRlMIIBIjANBgkqhkiG9w0BAQEFAAOC"
            + "AQ8AMIIBCgKCAQEAnI9P91jN/aegI279P40ixm9JerwC/NWkFFSe5A1bkHoAvtjF"
            + "k+r4LVR4IJIeefjxv1KjwQ2LsWE2LoCwQyCkzPYsZ02oqMchLuVhSh9hXRvRDf+t"
            + "GHQ2nCKworo1OdJwZvK2HMCdkAvJj1ZpBTDDXA0028PaIfSlu1MjoHLEmEUcXczV"
            + "w1lPbhanseuVZUecm8u1wzpzNx04hah8GRkGsVavP6xkgYkUzzarAzbpXmkeg0wr"
            + "O7kaixUpLjZmjpZfsRkcfuB5I/lsGq+R0kMYCZC/Q8C05EZ1CQqP3FaNtfXu3+Om"
            + "Dc3XFM25KEn1JbePZTKIpW7NmZtwMCjkD+LjAwIDAQABo4GRMIGOMB0GA1UdDgQW"
            + "BBTcKdvXavPF4w3WT56t3yBcnFpkGzBJBgNVHSMEQjBAgBTe/HXdZHFYqQJ+CedW"
            + "QrdaSSIAz6EkpCIwIDEeMBwGA1UEAwwVR29vZ2xlIENyeXB0QXV0aFZhdWx0ggIQ"
            + "ATASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBhjANBgkqhkiG9w0B"
            + "AQsFAAOCAgEAALHhT7NhqcO6fCcS2S3qT9h6175llbf9HGslweqIJJnDIfofRZB5"
            + "he3fRWh1oJWSRrxqNdw3XCMb7jV1c7p/gMI65PFzW6lg+XbWkvzZ6zZHlXsR5IBD"
            + "ExpYRkq6W02HmN+JXXNweKmycC1enicggjQuJlDaRXiWwZ9lJ9CGkHlPhW4tMlRc"
            + "ZvaMHO5bY/ivMCx+FiFuBs430ynCuJYE9Nh+v1ENBt03AsfPZUVuXDNvGOF+3ALs"
            + "Q2e4VDmM+lGW+/Ou4OsTwvHwdCPGG3fzF7e1uGcOI5v6VbySrZpGdgiw/UVUi6RH"
            + "ikqITmOLEhu68q6wGLwLbpG1LBvjrDFmx7lCUpUp3LNP78UtT3cVNa07wK+LmbIr"
            + "pGz24r6PFFJ2nD5jm0XkMR2DETRo6pacn0IyMPHH9JkzOndT1FHUcidc92GXB3EV"
            + "N/OywGDmrI89Z99NviwppKXtyWu4kYZ3XGoy/9x+pDoe4KJj8TwQAM6T8UsXWFor"
            + "+5717+RIFhWZGP6CboMRuYt4vQw25kUZtTysIkAjaX5bfHAGUpzvfGdf2qFBpsGG"
            + "Y3iP0jmLeo4pyGaFQq3B6yqxUXuWNEM8fLH+I38SINzTmtIU9gaefc7Yr0t5OSoX"
            + "bCh2e03PxYaQzLB6uyX+c4GbF2WXTsTdIXlMLPTRDTd4KM58058xp/s=";
    private static final String LEAF_CERT_1_BASE64 = ""
            + "MIIDTTCCATWgAwIBAgIGAWDpcHg7MA0GCSqGSIb3DQEBCwUAMC0xKzApBgNVBAMM"
            + "Ikdvb2dsZSBDcnlwdEF1dGhWYXVsdCBJbnRlcm1lZGlhdGUwHhcNMjUwODAxMDIw"
            + "MjUyWhcNMzAwNzMxMDIwMjUyWjApMScwJQYDVQQDDB5Hb29nbGUgQ3J5cHRBdXRo"
            + "VmF1bHQgSW5zdGFuY2UwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARkoPA3Ux61"
            + "SplLPqRuDWwetzrDmgwV6g+kzQHz30s587t4Z1Gn5k18RaUfMPF/lCo8IOeZZSlf"
            + "BVIWZ/SfS8cFo0IwQDAdBgNVHQ4EFgQUxCUPiZ+u/p6CsUQIHAj+mUoKmkMwHwYD"
            + "VR0jBBgwFoAU3vx13WRxWKkCfgnnVkK3WkkiAM8wDQYJKoZIhvcNAQELBQADggIB"
            + "AHdvuU6G93ZXphOxYV70bLu3y+4C5xK2cJrAJLU8UD+PN2SzRXKZ3kIdjxJaXJN2"
            + "lmjvkyhhuWovlJBsKo7J9iPw927/qzPCf+G0wQB8Xrc3lUBXlPHcENo2veqoe92a"
            + "I6k/MlhKQiVDC0xp0u81QqiC6qKe2n4tkcOQ2zxM+QtV3CfFmkMfXDBKr2EhYlf5"
            + "kEQyczsXxvIBEbNXqbeEGGCzlgRZw9yU9duQCiJTB7ndt2m6ur5mFoFiEvVvgdDF"
            + "D7FDs2lQR5tJYqnmJc8hOLwDf4cmuMUg4W67PopNSDvRaR8C1EaFK/a0Mq1JdRkL"
            + "HrK81vFEjJX1QXTlksa+qbAh/2oOihCwUYLp54IQxGnf4K9gNWmU1DbObmMQKLLS"
            + "uC9cTDxrw/kHTi6ccW37AzDoVr9N+4sxHwAM03BJMpaUKyrJDAion6o50mXo/xu1"
            + "WnCSseIcNJGJl4PEsr01FJ7/Iyu1h67Skfre5WRTuBe2YBo2WMwsugoQKTjrPwbk"
            + "gYM/jpfG3qktWm0jIbhJtSItw1DM4AvpvlqQT/RS70QlesXkUnY/Hgt5/HCRpxNa"
            + "1QYvU0YVVJbfdA2Y+BKh7BlShLF+1hUmM23iPLIwhI5GiYYdYuh8xGMUDzUydEg8"
            + "xBkiLNXmidbCjbOYMQO/RdNzZX7x+kR449fFl+0JfrXw";
    private static final String LEAF_CERT_2_BASE64 = ""
            + "MIICrzCCAZegAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwOjE4MDYGA1UEAwwvR29v"
            + "Z2xlIENyeXB0QXV0aFZhdWx0IEludGVybWVkaWF0ZSBJbnRlcm1lZGlhdGUwHhcN"
            + "MjUwODAxMDEzODQ0WhcNMzAwNzMxMDEzODQ0WjArMSkwJwYDVQQDDCBHb29nbGUg"
            + "Q3J5cHRBdXRoVmF1bHQgSW5zdGFuY2UgMjBZMBMGByqGSM49AgEGCCqGSM49AwEH"
            + "A0IABEiz4IlonT/quLH3jrjDT6L8z1pQnODge6giUzsyXy0yX87vgC9/S7fjM3Gu"
            + "hd+IqfJx1QU4m+mHu05DbudPGS2jgZgwgZUwDAYDVR0TAQH/BAIwADAOBgNVHQ8B"
            + "Af8EBAMCAwgwHQYDVR0OBBYEFGe7/Aksco1oBdN2PY9XpC46uev3MFYGA1UdIwRP"
            + "ME2AFNwp29dq88XjDdZPnq3fIFycWmQboTGkLzAtMSswKQYDVQQDDCJHb29nbGUg"
            + "Q3J5cHRBdXRoVmF1bHQgSW50ZXJtZWRpYXRlggIQADANBgkqhkiG9w0BAQsFAAOC"
            + "AQEABmoZZ76knG9+tgcn7J9RZKCl9B22SpxRBVXcZQW3WJr54jSg2foxjVSQ0dnO"
            + "ta2jpI8ZY9sHAQCVKr7MxrbWsIMaPmgPDGIiqgzur1e+g2KpANNZz6BJVqzROkT6"
            + "VWS1t4dzB3sUDkdwIzxyPm+qNJUZzycFg8kBIe1EbXK7hX2D+8dLNJwF/pH7Racz"
            + "olTXLDxTyNgYOXPNMoV/j9hlirXRDBJtw5ME7pcW8Exrt87C3Q6IIYBbtu9m0PCh"
            + "/LW7FCvXca+ezHLtEDsQKW2L9s4aj8oKghK8e0o6Yz69Lbbujw5sQMhk0xRO6Tm2"
            + "sbkgeBb042Gh9RH56s+LxWz8Mw==";

    /** The cert of the root CA. */
    static final X509Certificate ROOT_CA_TRUSTED = decodeBase64Cert(ROOT_CA_TRUSTED_BASE64);
    /** This root CA cert has a different Common Name than ROOT_CA_TRUSTED. */
    static final X509Certificate ROOT_CA_DIFFERENT_COMMON_NAME =
            decodeBase64Cert(ROOT_CA_DIFFERENT_COMMON_NAME_BASE64);
    /** This root CA cert has the same CN as ROOT_CA_TRUSTED, but a different public key. */
    static final X509Certificate ROOT_CA_DIFFERENT_KEY =
            decodeBase64Cert(ROOT_CA_DIFFERENT_KEY_BASE64);
    /** This intermediate CA cert is signed by the corresponding private key of ROOT_CA_TRUSTED. */
    static final X509Certificate INTERMEDIATE_CA_1 = decodeBase64Cert(INTERMEDIATE_CA_1_BASE64);
    /** This intermediate CA cert is signed by the private key of INTERMEDIATE_CA_1. */
    static final X509Certificate INTERMEDIATE_CA_2 = decodeBase64Cert(INTERMEDIATE_CA_2_BASE64);
    /** This leaf cert is signed by the corresponding private key of INTERMEDIATE_CA_1. */
    static final X509Certificate LEAF_CERT_1 = decodeBase64Cert(LEAF_CERT_1_BASE64);
    /** This leaf cert is signed by the corresponding private key of INTERMEDIATE_CA_2. */
    static final X509Certificate LEAF_CERT_2 = decodeBase64Cert(LEAF_CERT_2_BASE64);

    private static X509Certificate decodeBase64Cert(String str) {
        try {
            byte[] bytes = Base64.getDecoder().decode(str);
            CertificateFactory cf = CertificateFactory.getInstance("X.509");
            return (X509Certificate) cf.generateCertificate(new ByteArrayInputStream(bytes));
        } catch (Exception e) {
            throw new RuntimeException(e.getMessage());
        }
    }

    static final Date DATE_ALL_CERTS_VALID = new Date(1754438400000L); // Aug 6, 2025
    static final Date DATE_LEAF_CERT_2_EXPIRED = new Date(1547254989001L); // Jan 12, 2019
    static final Date DATE_INTERMEDIATE_CA_2_EXPIRED = new Date(1673397483001L); // Jan 11, 2023

    static InputStream openTestFile(String relativePath) throws Exception {
        Context context = InstrumentationRegistry.getContext();
        return context.getResources().getAssets().open(TEST_FILE_FOLDER_NAME + "/" + relativePath);
    }

    static byte[] readTestFile(String relativePath) throws Exception {
        InputStream in = openTestFile(relativePath);
        return ByteStreams.toByteArray(in);
    }
}
