/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.wm.shell.windowdecor;

import static android.view.InputDevice.SOURCE_TOUCHSCREEN;
import static android.view.MotionEvent.ACTION_CANCEL;
import static android.view.MotionEvent.ACTION_DOWN;
import static android.view.MotionEvent.ACTION_HOVER_ENTER;
import static android.view.MotionEvent.ACTION_HOVER_EXIT;
import static android.view.MotionEvent.ACTION_HOVER_MOVE;
import static android.view.MotionEvent.ACTION_MOVE;
import static android.view.MotionEvent.ACTION_POINTER_UP;
import static android.view.MotionEvent.ACTION_UP;

import android.annotation.NonNull;
import android.graphics.PointF;
import android.util.Log;
import android.util.SparseBooleanArray;
import android.view.MotionEvent;
import android.view.View;
import android.view.ViewGroup;

import androidx.annotation.Nullable;

import com.android.window.flags.Flags;

/**
 * A detector for touch inputs that differentiates between drag and click inputs. It receives a flow
 * of {@link MotionEvent} and generates a new flow of motion events with slop in consideration to
 * the event handler. In particular, it always passes down, up and cancel events. It'll pass move
 * events only when there is at least one move event that's beyond the slop threshold.
 *
 * <p>This class assumes the event handler only handles the drag gesture from a specific pointer. It
 * aggressively filters irrelevant events and pointers, so that the event handler receives a clean
 * and valid flow of {@link MotionEvent} with only one pointer from one device for each drag
 * gesture.
 *
 * <p>All touch events must be passed through this class to track a drag event.
 */
public class DragDetector {
    private static final String TAG = "DragDetector";

    private final MotionEventHandler mEventHandler;

    /**
     * Mapping from device IDs to whether it is the primary device this drag detector is tracking.
     *
     * <p>If a device ID is missing in the mapping, then there isn't an active gesture dispatched
     * from this device. If a device ID maps to {@code true}, then this drag gesture is tracking
     * events generated by this device. If a device ID maps to {@code false}, then there is an
     * ongoing gesture dispatched to this drag detector, but this drag detector is discarding that
     * gesture because another active gesture is happening at the same time.
     *
     * <p>This field isn't reset in {@link #resetState()} because this detector shouldn't respond to
     * any events until all gestures from all devices are finished.
     */
    private final SparseBooleanArray mDeviceIdsWithOngoingGestures =
            new SparseBooleanArray(2 /* initialCapacity */);

    private final PointF mInputDownPoint = new PointF();
    private int mTouchSlop;
    private boolean mIsDragEvent;
    private int mDragPointerId = -1;
    private final long mHoldToDragMinDurationMs;
    private boolean mDidStrayBeforeFullHold;
    private boolean mDidHoldForMinDuration;

    private boolean mResultOfDownAction;

    private MotionEvent mInterceptedDown;
    private int mInterceptingViewId = View.NO_ID;

    /**
     * Initialises a drag detector.
     *
     * @param eventHandler drag event handler.
     * @param holdToDragMinDurationMs hold to drag duration.
     * @param touchSlop touch slope threshold.
     */
    public DragDetector(@NonNull MotionEventHandler eventHandler, long holdToDragMinDurationMs,
            int touchSlop) {
        resetState();
        mEventHandler = eventHandler;
        mHoldToDragMinDurationMs = holdToDragMinDurationMs;
        mTouchSlop = touchSlop;
    }

    /**
     * Passes events {@link ViewGroup#onInterceptTouchEvent(MotionEvent)} receives if this drag
     * detector is used to intercept drags. This receives the event flow of the intercepted events.
     * The caller is responsible to pass events {@link View#onTouchEvent(MotionEvent)} receives to
     * {@link #onMotionEvent(MotionEvent)}.
     *
     * <p>It only intercepts drags. The caller is responsible for all other gestures.
     *
     * @param v the view group that receives the intercepted event
     * @param ev the intercepted event
     * @return {@code true} if intercepted, {@code false} otherwise
     */
    public boolean onInterceptTouchEvent(ViewGroup v, MotionEvent ev) {
        if (ev.isSynthesizedTouchpadGesture()) {
            // Touchpad finger gestures are ignored.
            return false;
        }

        switch (ev.getActionMasked()) {
            case ACTION_DOWN: {
                if (Flags.filterEventsFromIrrelevantDevicesInDragMoveResize()) {
                    mDeviceIdsWithOngoingGestures.put(
                            ev.getDeviceId(), mDeviceIdsWithOngoingGestures.size() == 0);
                    if (!mDeviceIdsWithOngoingGestures.get(ev.getDeviceId())) {
                        return false;
                    }
                }
                updateStateForDown(ev);
                mInterceptedDown = ev.copy();
                // We never know if this down is going to be a drag gesture.
                return false;
            }
            case ACTION_MOVE: {
                if (Flags.filterEventsFromIrrelevantDevicesInDragMoveResize()
                        && !mDeviceIdsWithOngoingGestures.get(ev.getDeviceId())) {
                    return false;
                }
                if (mDragPointerId == -1) {
                    // The primary pointer was lifted, ignore the rest of the gesture.
                    return false;
                }
                final int dragPointerIndex = ev.findPointerIndex(mDragPointerId);
                // TODO(b/400635953): Separate the app header and its buttons'
                // touch listeners so they're not handled by the same DragDetector.
                if (dragPointerIndex == -1) {
                    Log.w(TAG, "Invalid pointer index on intercepting ACTION_MOVE. Drag"
                            + " pointer id: " + mDragPointerId);
                    return false;
                }
                if (!mIsDragEvent) {
                    updateDragState(ev, dragPointerIndex);
                }
                if (mIsDragEvent && mInterceptedDown != null) {
                    mResultOfDownAction = mEventHandler.handleMotionEvent(v, mInterceptedDown);
                    mInterceptedDown = null;
                    mInterceptingViewId = v.getId();
                }
                // The event handler should only be notified about 'move' events if a drag has been
                // detected.
                return mIsDragEvent;
            }
            case ACTION_POINTER_UP: {
                if (Flags.filterEventsFromIrrelevantDevicesInDragMoveResize()
                        && !mDeviceIdsWithOngoingGestures.get(ev.getDeviceId())) {
                    return false;
                }
                if (mDragPointerId == -1) {
                    // The primary pointer was lifted, ignore the rest of the gesture.
                    return false;
                }
                if (mDragPointerId != ev.getPointerId(ev.getActionIndex())) {
                    // Ignore a secondary pointer being lifted.
                    return false;
                }
                // The primary pointer that triggered ACTION_DOWN is being lifted before we
                // intercept anything.
                mDragPointerId = -1;
                return false;
            }
            case ACTION_UP:
            case ACTION_CANCEL: {
                if (Flags.filterEventsFromIrrelevantDevicesInDragMoveResize()) {
                    final boolean isEventFromPrimaryDevice =
                            mDeviceIdsWithOngoingGestures.get(ev.getDeviceId());
                    mDeviceIdsWithOngoingGestures.delete(ev.getDeviceId());
                    if (!isEventFromPrimaryDevice) {
                        return false;
                    }
                }
                final boolean wasDrag = mIsDragEvent;
                resetState();
                return wasDrag;
            }
            default: {
                return mIsDragEvent;
            }
        }
    }

    /**
     * The receiver of the {@link MotionEvent} flow.
     *
     * @return the result returned by {@link #mEventHandler}, or the result when
     * {@link #mEventHandler} handles the previous down event if the event shouldn't be passed
     */
    public boolean onMotionEvent(MotionEvent ev) {
        return onMotionEvent(null /* view */, ev);
    }

    /**
     * The receiver of the {@link MotionEvent} flow.
     *
     * @return the result returned by {@link #mEventHandler}, or the result when
     * {@link #mEventHandler} handles the previous down event if the event shouldn't be passed
     */
    public boolean onMotionEvent(@Nullable View v, MotionEvent ev) {
        if (ev.isSynthesizedTouchpadGesture()) {
            // Touchpad finger gestures are ignored.
            return false;
        }
        // Due to the current code structure, one instance of this class can be used to filter
        // events for multiple views. Particularly, if a parent view group starts to intercept a
        // gesture, child views of it receives cancel events. We don't want to pass that cancel
        // event to the event handler.
        // TODO(b/400635953): Remove this logic after we use a separate DragDetector for each view.
        if (mInterceptingViewId != View.NO_ID && (v == null || mInterceptingViewId != v.getId())) {
            return false;
        }
        switch (ev.getActionMasked()) {
            case ACTION_DOWN: {
                // We could receive the same down event in onInterceptTouchEvent, and we shouldn't
                // treat it as an irrelevant device.
                if (Flags.filterEventsFromIrrelevantDevicesInDragMoveResize()) {
                    final boolean isEventFromPrimaryDevice =
                            mDeviceIdsWithOngoingGestures.size() == 1
                                    && mDeviceIdsWithOngoingGestures.keyAt(0) == ev.getDeviceId();
                    if (!isEventFromPrimaryDevice) {
                        mDeviceIdsWithOngoingGestures.put(
                                ev.getDeviceId(), mDeviceIdsWithOngoingGestures.size() == 0);
                    }
                    if (!mDeviceIdsWithOngoingGestures.get(ev.getDeviceId())) {
                        return false;
                    }
                }
                updateStateForDown(ev);
                mResultOfDownAction = mEventHandler.handleMotionEvent(v, ev);
                return mResultOfDownAction;
            }
            case ACTION_MOVE: {
                if (Flags.filterEventsFromIrrelevantDevicesInDragMoveResize()
                        && !mDeviceIdsWithOngoingGestures.get(ev.getDeviceId())) {
                    return false;
                }
                if (mDragPointerId == -1) {
                    // The primary pointer was lifted, ignore the rest of the gesture.
                    return mResultOfDownAction;
                }
                final int dragPointerIndex = ev.findPointerIndex(mDragPointerId);
                // TODO(b/400635953): Separate the app header and its buttons'
                // touch listeners so they're not handled by the same DragDetector.
                if (dragPointerIndex == -1) {
                    Log.w(TAG, "Invalid pointer index on ACTION_MOVE. Drag"
                        + " pointer id: " + mDragPointerId);
                    return mResultOfDownAction;
                }
                if (!mIsDragEvent) {
                    updateDragState(ev, dragPointerIndex);
                }
                // The event handler should only be notified about 'move' events if a drag has been
                // detected.
                if (!mIsDragEvent) {
                    return mResultOfDownAction;
                }
                return mEventHandler.handleMotionEvent(v,
                        getSinglePointerEvent(ev, mDragPointerId));
            }
            case ACTION_HOVER_ENTER:
            case ACTION_HOVER_MOVE:
            case ACTION_HOVER_EXIT: {
                // Hover events are only passed when there isn't an ongoing drag gesture.
                if (Flags.filterEventsFromIrrelevantDevicesInDragMoveResize()
                        && mDeviceIdsWithOngoingGestures.size() != 0) {
                    return false;
                }
                return mEventHandler.handleMotionEvent(v,
                        getSinglePointerEvent(ev, mDragPointerId));
            }
            case ACTION_POINTER_UP: {
                if (Flags.filterEventsFromIrrelevantDevicesInDragMoveResize()
                        && !mDeviceIdsWithOngoingGestures.get(ev.getDeviceId())) {
                    return false;
                }
                if (mDragPointerId == -1) {
                    // The primary pointer was lifted, ignore the rest of the gesture.
                    return mResultOfDownAction;
                }
                if (mDragPointerId != ev.getPointerId(ev.getActionIndex())) {
                    // Ignore a secondary pointer being lifted.
                    return mResultOfDownAction;
                }
                // The primary pointer is being lifted.
                final int dragPointerId = mDragPointerId;
                mDragPointerId = -1;
                return mEventHandler.handleMotionEvent(v, getSinglePointerEvent(ev, dragPointerId));
            }
            case ACTION_UP:
            case ACTION_CANCEL: {
                if (Flags.filterEventsFromIrrelevantDevicesInDragMoveResize()) {
                    final boolean isEventFromPrimaryDevice =
                            mDeviceIdsWithOngoingGestures.get(ev.getDeviceId());
                    mDeviceIdsWithOngoingGestures.delete(ev.getDeviceId());
                    if (!isEventFromPrimaryDevice) {
                        return false;
                    }
                }
                final int dragPointerId = mDragPointerId;
                resetState();
                if (dragPointerId == -1) {
                    // The primary pointer was lifted, ignore the rest of the gesture.
                    return mResultOfDownAction;
                }
                return mEventHandler.handleMotionEvent(v, getSinglePointerEvent(ev, dragPointerId));
            }
            default:
                // Ignore other events.
                return mResultOfDownAction;
        }
    }

    private static MotionEvent getSinglePointerEvent(MotionEvent ev, int pointerId) {
        return ev.getPointerCount() > 1 ? ev.split(1 << pointerId) : ev;
    }

    private void updateStateForDown(MotionEvent downEvent) {
        mDragPointerId = downEvent.getPointerId(0);
        final float rawX = downEvent.getRawX(0);
        final float rawY = downEvent.getRawY(0);
        mInputDownPoint.set(rawX, rawY);
    }

    private void updateDragState(MotionEvent ev, int dragPointerIndex) {
        final boolean isTouchScreen =
                (ev.getSource() & SOURCE_TOUCHSCREEN) == SOURCE_TOUCHSCREEN;
        final float dx = ev.getRawX(dragPointerIndex) - mInputDownPoint.x;
        final float dy = ev.getRawY(dragPointerIndex) - mInputDownPoint.y;
        final boolean pastTouchSlop = Math.hypot(dx, dy) > mTouchSlop;

        if (!isTouchScreen || mHoldToDragMinDurationMs <= 0) {
            // No need to apply the hold-to-drag logic if the event is from a
            // non-touchscreen source like mouse/touchpad, or the minimum hold duration
            // is not set to a positive value.
            mDidHoldForMinDuration = true;
        } else {
            final boolean withinHoldRegion = !pastTouchSlop;
            final float dt = ev.getEventTime() - ev.getDownTime();
            if (!withinHoldRegion && dt < mHoldToDragMinDurationMs) {
                // Mark as having strayed so that in case the (x,y) ends up in the
                // original position we know it's not actually valid.
                mDidStrayBeforeFullHold = true;
            }
            if (!mDidStrayBeforeFullHold && dt >= mHoldToDragMinDurationMs) {
                mDidHoldForMinDuration = true;
            }
        }

        // Touches generate noisy moves, so only once the move is past the touch
        // slop threshold should it be considered a drag.
        mIsDragEvent = mDidHoldForMinDuration && pastTouchSlop;
    }

    void setTouchSlop(int touchSlop) {
        mTouchSlop = touchSlop;
    }

    private void resetState() {
        mIsDragEvent = false;
        mInputDownPoint.set(0, 0);
        mDragPointerId = -1;
        mResultOfDownAction = false;
        mDidStrayBeforeFullHold = false;
        mDidHoldForMinDuration = false;
        mInterceptedDown = null;
        mInterceptingViewId = View.NO_ID;
    }

    /**
     * Interface to be implemented by the class using the DragDetector for callback.
     */
    public interface MotionEventHandler {
        /**
         * Called back when drag is detected to notify the implementing class to handle drag events.
         * @param v view on which the input arrived.
         * @param ev motion event that resulted in drag.
         * @return whether this was a drag event or not.
         */
        boolean handleMotionEvent(@Nullable View v, MotionEvent ev);
    }
}
