/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.systemui.privacy

import android.content.Context
import com.android.systemui.res.R

/**
 * Utility class to create the content description for the privacy chip based on the types. This
 * class is used to create a localized list of the different privacy types. It's expected that the
 * string generated by this class is used in a sentence with a string like
 * [R.string.ongoing_privacy_chip_content_multiple_apps].
 */
class PrivacyChipContentDescriptionGenerator(private val context: Context) {
    private val separator = context.getString(R.string.ongoing_privacy_dialog_separator)
    private val lastSeparator = context.getString(R.string.ongoing_privacy_dialog_last_separator)

    private fun <T> List<T>.joinWithAnd(): StringBuilder {
        return subList(0, size - 1).joinTo(StringBuilder(), separator = separator).apply {
            append(lastSeparator)
            append(this@joinWithAnd.last())
        }
    }

    /**
     * Generates the content description for the privacy types.
     *
     * They will be deduplicated and sorted. If there's a single element, the content description is
     * just the name associated with that element. For more than one, they will be separated using
     * [R.string.ongoing_privacy_dialog_separator] for intermediate separators, and
     * [R.string.ongoing_privacy_dialog_last_separator] for the last separator.
     */
    fun joinTypesForContentDescription(privacyTypes: Collection<PrivacyType>): String {
        val sortedTypes = privacyTypes.distinct().sorted()
        return when (sortedTypes.size) {
            0 -> ""
            1 -> sortedTypes[0].getName(context)
            else -> sortedTypes.map { it.getName(context) }.joinWithAnd().toString()
        }
    }
}
