#!/usr/bin/env python3
#
# Copyright (C) 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Tool to generate a policy file to keep all AIDL parcelables.

Usage:
$ANDROID_BUILD_TOP/frameworks/base/ravenwood/scripts/gen-aidl-policy.py \
  $ANDROID_BUILD_TOP/frameworks/base/ravenwood/texts/ravenwood-aidl-policies.txt \
  $ANDROID_BUILD_TOP/frameworks/base
"""

import glob
import sys
import re

# Regex to find the package declaration
# Example: package com.example.foo;
package_pattern = re.compile(r"^\s*package\s+([a-zA-Z0-9_.]+)\s*;")

# Regex to find the main parcelable definition
# Example: parcelable MyData { ... }
class_pattern = re.compile(r"^\s*parcelable\s+([a-zA-Z0-9_.]+)\s*\{")


def parse_parcelable_aidl(aidl: str) -> str | None:
    package_name = None
    class_name = None

    with open(aidl) as f:
        for line in f:
            # Search for package name if not already found
            if not package_name:
                match = package_pattern.match(line)
                if match:
                    package_name = match.group(1)

            # Search for class name if not already found
            if not class_name:
                match = class_pattern.match(line)
                if match:
                    class_name = match.group(1).replace(".", "#")

            # Stop early if both are found
            if package_name and class_name:
                return f"{package_name}.{class_name}"

    return None


if __name__ == "__main__":
    aidl_classes: list[str] = []

    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <policy_file> <src_dir>...")
        exit(1)

    for src_dir in sys.argv[2:]:
        for aidl in glob.glob(f"{src_dir}/**/*.aidl", recursive=True):
            clz = parse_parcelable_aidl(aidl)
            if clz:
                aidl_classes.append(clz)

    aidl_classes.sort()

    with open(sys.argv[1], "w") as policy:
        print("# Auto generated by gen-aidl-policy.py\n", file=policy)
        for clz in aidl_classes:
            print(f"class {clz} keepclass", file=policy)
