/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.server.security.advancedprotection.features;

import android.content.Context;
import android.annotation.IntDef;
import android.os.BugreportManager;
import android.os.BugreportParams;
import android.os.SystemClock;
import android.util.Slog;
import java.util.HashMap;
import java.util.Map;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import android.util.SparseLongArray;

class UsbDataBugReportHelper {
    private static final String TAG = "AdvancedProtectionUsbBugReportHelper";
    private static final String BUG_REPORT_TITLE =
            "Advanced Protection USB Data Protection Error Occurred";
    private static final String BUG_REPORT_DESCRIPTION =
            "Bug report generated by the Advanced Protection USB Data Protection due to: ";

    // Set to 7 days but Advanced Protection reboots every 72 hours,
    private static final long MIN_TIME_BETWEEN_BUG_REPORTS_MILLIS =
            1000 * 60 * 60 * 24 * 7; // 7 days

    public static final int REPORT_REASON_FAILURE_TO_ENABLE_USB_DATA = 0;
    public static final int REPORT_REASON_FAILURE_TO_DISABLE_USB_DATA = 1;

    @IntDef(
            prefix = {"REPORT_REASON_"},
            value = {
                REPORT_REASON_FAILURE_TO_ENABLE_USB_DATA,
                REPORT_REASON_FAILURE_TO_DISABLE_USB_DATA
            })
    @Retention(RetentionPolicy.SOURCE)
    public @interface ReportReason {}

    private static final Map<Integer, String> BUGREPORT_REASON_TO_TITLE =
            Map.of(
                    REPORT_REASON_FAILURE_TO_ENABLE_USB_DATA,
                    "Failure to enable USB data signal",
                    REPORT_REASON_FAILURE_TO_DISABLE_USB_DATA,
                    "Failure to disable USB data signal");

    private final Context mContext;
    private final BugreportManager mBugReportManager;
    private final SparseLongArray mLastBugReportTracker = new SparseLongArray();

    public UsbDataBugReportHelper(Context context) {
        mContext = context;
        mBugReportManager = mContext.getSystemService(BugreportManager.class);
    }

    public void report(@ReportReason int reason) {
        if (mLastBugReportTracker.get(reason, -1) != -1) {
            long lastReportTime = mLastBugReportTracker.get(reason);
            long timeSinceLastReport = SystemClock.uptimeMillis() - lastReportTime;
            if (timeSinceLastReport < MIN_TIME_BETWEEN_BUG_REPORTS_MILLIS) {
                Slog.d(TAG, "Not reporting bugreport: " + reason + " due to rate limiting");
                return;
            }
        }

        BugreportParams params = new BugreportParams(BugreportParams.BUGREPORT_MODE_FULL);
        try {
            mBugReportManager.requestBugreport(
                    params,
                    BUG_REPORT_TITLE,
                    BUG_REPORT_DESCRIPTION + BUGREPORT_REASON_TO_TITLE.get(reason));
        } catch (RuntimeException e) {
            Slog.e(TAG, "Error taking bugreport", e);
        }
        mLastBugReportTracker.put(reason, SystemClock.uptimeMillis());
    }
}
