/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.server.pm.verify.developer;

import static android.content.pm.verify.developer.DeveloperVerificationStatus.APP_METADATA_VERIFICATION_STATUS_GOOD;
import static android.content.pm.verify.developer.DeveloperVerificationStatus.APP_METADATA_VERIFICATION_STATUS_UNDEFINED;
import static android.content.pm.verify.developer.DeveloperVerificationStatus.AppMetadataVerificationStatus;

import android.annotation.IntDef;

import com.android.internal.util.DataClass;

/**
 * Internal data class to track the developer verification status of an app, as part of the
 * package state.
 * <p>Note: Part of the class is auto-generated with codegen.</p>
 */
@DataClass(genToString = true, genSetters = true, genBuilder = false)
public class DeveloperVerificationStatusInternal {
    public static final int STATUS_UNKNOWN = 0;
    public static final int STATUS_COMPLETED_WITH_PASS = 1;
    public static final int STATUS_COMPLETED_WITH_REJECT = 2;
    public static final int STATUS_INCOMPLETE_UNKNOWN = 3;
    public static final int STATUS_INCOMPLETE_NETWORK_UNAVAILABLE = 4;
    public static final int STATUS_TIMEOUT = 5;
    public static final int STATUS_DISCONNECTED = 6;
    public static final int STATUS_INFEASIBLE = 7;

    /**
     * Default status when the verification has not been performed.
     */
    public static DeveloperVerificationStatusInternal UNKNOWN =
            new DeveloperVerificationStatusInternal(
                    STATUS_UNKNOWN, APP_METADATA_VERIFICATION_STATUS_UNDEFINED, false);
    /**
     * Internal status of the developer verification, which includes not only the response from
     * the verifier, but also any error state that may have occurred instead of a response from
     * the verifier.
     */
    private @Status int mInternalStatus = STATUS_UNKNOWN;
    /**
     * The App Metadata verification result received from the verifier.
     */
    private @AppMetadataVerificationStatus int
            mAppMetadataVerificationStatus = APP_METADATA_VERIFICATION_STATUS_UNDEFINED;
    /**
     * Whether a lite verification was conducted on the installation.
     */
    private boolean mLiteVerification = false;

    public boolean isAppMetadataVerified() {
        return mAppMetadataVerificationStatus == APP_METADATA_VERIFICATION_STATUS_GOOD;
    }

    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/frameworks/base/services/core/java/com/android/server/pm/verify/developer/DeveloperVerificationStatusInternal.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    @IntDef(prefix = "STATUS_", value = {
        STATUS_UNKNOWN,
        STATUS_COMPLETED_WITH_PASS,
        STATUS_COMPLETED_WITH_REJECT,
        STATUS_INCOMPLETE_UNKNOWN,
        STATUS_INCOMPLETE_NETWORK_UNAVAILABLE,
        STATUS_TIMEOUT,
        STATUS_DISCONNECTED,
        STATUS_INFEASIBLE
    })
    @java.lang.annotation.Retention(java.lang.annotation.RetentionPolicy.SOURCE)
    @DataClass.Generated.Member
    public @interface Status {}

    @DataClass.Generated.Member
    public static String statusToString(@Status int value) {
        switch (value) {
            case STATUS_UNKNOWN:
                    return "STATUS_UNKNOWN";
            case STATUS_COMPLETED_WITH_PASS:
                    return "STATUS_COMPLETED_WITH_PASS";
            case STATUS_COMPLETED_WITH_REJECT:
                    return "STATUS_COMPLETED_WITH_REJECT";
            case STATUS_INCOMPLETE_UNKNOWN:
                    return "STATUS_INCOMPLETE_UNKNOWN";
            case STATUS_INCOMPLETE_NETWORK_UNAVAILABLE:
                    return "STATUS_INCOMPLETE_NETWORK_UNAVAILABLE";
            case STATUS_TIMEOUT:
                    return "STATUS_TIMEOUT";
            case STATUS_DISCONNECTED:
                    return "STATUS_DISCONNECTED";
            case STATUS_INFEASIBLE:
                    return "STATUS_INFEASIBLE";
            default: return Integer.toHexString(value);
        }
    }

    @DataClass.Generated.Member
    public DeveloperVerificationStatusInternal(
            @Status int internalStatus,
            @AppMetadataVerificationStatus int appMetadataVerificationStatus,
            boolean liteVerification) {
        this.mInternalStatus = internalStatus;

        if (!(mInternalStatus == STATUS_UNKNOWN)
                && !(mInternalStatus == STATUS_COMPLETED_WITH_PASS)
                && !(mInternalStatus == STATUS_COMPLETED_WITH_REJECT)
                && !(mInternalStatus == STATUS_INCOMPLETE_UNKNOWN)
                && !(mInternalStatus == STATUS_INCOMPLETE_NETWORK_UNAVAILABLE)
                && !(mInternalStatus == STATUS_TIMEOUT)
                && !(mInternalStatus == STATUS_DISCONNECTED)
                && !(mInternalStatus == STATUS_INFEASIBLE)) {
            throw new java.lang.IllegalArgumentException(
                    "internalStatus was " + mInternalStatus + " but must be one of: "
                            + "STATUS_UNKNOWN(" + STATUS_UNKNOWN + "), "
                            + "STATUS_COMPLETED_WITH_PASS(" + STATUS_COMPLETED_WITH_PASS + "), "
                            + "STATUS_COMPLETED_WITH_REJECT(" + STATUS_COMPLETED_WITH_REJECT + "), "
                            + "STATUS_INCOMPLETE_UNKNOWN(" + STATUS_INCOMPLETE_UNKNOWN + "), "
                            + "STATUS_INCOMPLETE_NETWORK_UNAVAILABLE(" + STATUS_INCOMPLETE_NETWORK_UNAVAILABLE + "), "
                            + "STATUS_TIMEOUT(" + STATUS_TIMEOUT + "), "
                            + "STATUS_DISCONNECTED(" + STATUS_DISCONNECTED + "), "
                            + "STATUS_INFEASIBLE(" + STATUS_INFEASIBLE + ")");
        }

        this.mAppMetadataVerificationStatus = appMetadataVerificationStatus;
        com.android.internal.util.AnnotationValidations.validate(
                AppMetadataVerificationStatus.class, null, mAppMetadataVerificationStatus);
        this.mLiteVerification = liteVerification;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public @Status int getInternalStatus() {
        return mInternalStatus;
    }

    @DataClass.Generated.Member
    public @AppMetadataVerificationStatus int getAppMetadataVerificationStatus() {
        return mAppMetadataVerificationStatus;
    }

    @DataClass.Generated.Member
    public boolean isLiteVerification() {
        return mLiteVerification;
    }

    @DataClass.Generated.Member
    public @android.annotation.NonNull DeveloperVerificationStatusInternal setInternalStatus(@Status int value) {
        mInternalStatus = value;

        if (!(mInternalStatus == STATUS_UNKNOWN)
                && !(mInternalStatus == STATUS_COMPLETED_WITH_PASS)
                && !(mInternalStatus == STATUS_COMPLETED_WITH_REJECT)
                && !(mInternalStatus == STATUS_INCOMPLETE_UNKNOWN)
                && !(mInternalStatus == STATUS_INCOMPLETE_NETWORK_UNAVAILABLE)
                && !(mInternalStatus == STATUS_TIMEOUT)
                && !(mInternalStatus == STATUS_DISCONNECTED)
                && !(mInternalStatus == STATUS_INFEASIBLE)) {
            throw new java.lang.IllegalArgumentException(
                    "internalStatus was " + mInternalStatus + " but must be one of: "
                            + "STATUS_UNKNOWN(" + STATUS_UNKNOWN + "), "
                            + "STATUS_COMPLETED_WITH_PASS(" + STATUS_COMPLETED_WITH_PASS + "), "
                            + "STATUS_COMPLETED_WITH_REJECT(" + STATUS_COMPLETED_WITH_REJECT + "), "
                            + "STATUS_INCOMPLETE_UNKNOWN(" + STATUS_INCOMPLETE_UNKNOWN + "), "
                            + "STATUS_INCOMPLETE_NETWORK_UNAVAILABLE(" + STATUS_INCOMPLETE_NETWORK_UNAVAILABLE + "), "
                            + "STATUS_TIMEOUT(" + STATUS_TIMEOUT + "), "
                            + "STATUS_DISCONNECTED(" + STATUS_DISCONNECTED + "), "
                            + "STATUS_INFEASIBLE(" + STATUS_INFEASIBLE + ")");
        }

        return this;
    }

    @DataClass.Generated.Member
    public @android.annotation.NonNull DeveloperVerificationStatusInternal setAppMetadataVerificationStatus(@AppMetadataVerificationStatus int value) {
        mAppMetadataVerificationStatus = value;
        com.android.internal.util.AnnotationValidations.validate(
                AppMetadataVerificationStatus.class, null, mAppMetadataVerificationStatus);
        return this;
    }

    @DataClass.Generated.Member
    public @android.annotation.NonNull DeveloperVerificationStatusInternal setLiteVerification( boolean value) {
        mLiteVerification = value;
        return this;
    }

    @Override
    @DataClass.Generated.Member
    public String toString() {
        // You can override field toString logic by defining methods like:
        // String fieldNameToString() { ... }

        return "DeveloperVerificationStatusInternal { " +
                "internalStatus = " + statusToString(mInternalStatus) + ", " +
                "appMetadataVerificationStatus = " + mAppMetadataVerificationStatus + ", " +
                "liteVerification = " + mLiteVerification +
        " }";
    }

    @DataClass.Generated(
            time = 1750110038030L,
            codegenVersion = "1.0.23",
            sourceFile = "frameworks/base/services/core/java/com/android/server/pm/verify/developer/DeveloperVerificationStatusInternal.java",
            inputSignatures = "public static final  int STATUS_UNKNOWN\npublic static final  int STATUS_COMPLETED_WITH_PASS\npublic static final  int STATUS_COMPLETED_WITH_REJECT\npublic static final  int STATUS_INCOMPLETE_UNKNOWN\npublic static final  int STATUS_INCOMPLETE_NETWORK_UNAVAILABLE\npublic static final  int STATUS_TIMEOUT\npublic static final  int STATUS_DISCONNECTED\npublic static final  int STATUS_INFEASIBLE\npublic static  com.android.server.pm.verify.developer.DeveloperVerificationStatusInternal UNKNOWN\nprivate @com.android.server.pm.verify.developer.DeveloperVerificationStatusInternal.Status int mInternalStatus\nprivate @android.content.pm.verify.developer.DeveloperVerificationStatus.AppMetadataVerificationStatus int mAppMetadataVerificationStatus\nprivate  boolean mLiteVerification\nclass DeveloperVerificationStatusInternal extends java.lang.Object implements []\n@com.android.internal.util.DataClass(genToString=true, genSetters=true, genBuilder=false)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
