# TODO: Create this file in gradle
targetSdkVersionInt=10000
targetSdkVersionRaw=
packageName=
targetPackageName=
instrumentationClass=
moduleName=RavenwoodGradleSample
resourceApk=build/intermediates/apk_for_local_test/debugUnitTest/packageDebugUnitTestForUnitTest/apk-for-local-test.ap_
targetResourceApk=
